### ISSUE TITLE
Add image renaming with Llava

### ISSUE THREAD

**Issue by tommitytom** [ozgrozer/ai-renamer#1]
It should be pretty simple to add Llava support, since it just accepts the contents of an image as a base64 image url. Could add it to `readFileContent.js` as a special case like `.pdf`

**Comment by ozgrozer** [comment]
Oh thank you for the feedback. I was wondering how to upload photos to Llava with Ollama APIs. Didn't know it was that easy. I'll definitely do that.

**Comment by ozgrozer** [comment]
Now it supports images too.
