### ISSUE TITLE
Dataseries json will fail.

### ISSUE THREAD

**Issue by HorusPi** [ozgrozer/ai-renamer#2]
Json data documents constructed as such 
[{"Fecha":"05/09/2021 17:24:51","Resultado":251.05},{"Fecha":"05/09/2021 17:25:12","Resultado":270.09},....]

Fails with this message
ENOENT: no such file or directory, rename 'E:\Documentos\test\mediciones-potencia.json' -> 'E:\Documentos\test\Here is a concise, descriptive filename in kebab-case format:

`2021-09-05-scores.json`

This filename includes the date (YYYY-MM-DD) and the type of data being stored (scores). The `.json` extension indicates that the file contains JSON-formatted data..json'

Not sure why it fails but here it is.
And thanks for the work!

**Comment by ozgrozer** [comment]
What LLM you're using? Sometimes it makes the filenames like in the first example you gave.

**Comment by HorusPi** [comment]
> What LLM you're using? Sometimes it makes the filenames like in the first example you gave.

Llama3:8b

**Comment by ozgrozer** [comment]
I'm trying to figure out what causes that long filenames. I think it's because of large files.

**Comment by HorusPi** [comment]
> I'm trying to figure out what causes that long filenames. I think it's because of large files.

Unlikely , the first was 9k (measures json) ,an the second is 13k (html)

**Comment by ozgrozer** [comment]
Sometimes LLMs are just not obeying the prompt. Maybe prompt needs to be updated.

**Comment by ozgrozer** [comment]
I've made an update to slice the LLM result [here](https://github.com/ozgrozer/ai-renamer/commit/0dc7fdb86ca8b10120843b610f486858a26798aa). Even though it generates a long name, it won't add to the filename.
