### ISSUE TITLE
Images given same filename result in previously processed images to be deleted. 

### ISSUE THREAD

**Issue by mgalde** [ozgrozer/ai-renamer#5]
Ai-renamer focused on the screenshot folder and processed some images with the same file name. This resulted in the photos being overwritten when the application was completed. 
![Screenshot_20240708_140943](https://github.com/ozgrozer/ai-renamer/assets/30883926/894ea90f-07f4-418f-9a93-b2141b9989c9)

**Comment by ozgrozer** [comment]
Thank you for letting me know. I'll fix that.

**Comment by ozgrozer** [comment]
OK I've fixed it in this [commit](https://github.com/ozgrozer/ai-renamer/commit/30a4f0eddf46c2fbe3ea30d20b193e0ffe301fb5) but you should be using Llava for images. Llama cannot read the images. That's probably why it was trying to use the same filename.

**Comment by mgalde** [comment]
Awesome thank you. Awesome project.
